### ISSUE TITLE
Incompatible with Vanilla+ Biomes

### ISSUE THREAD

**Issue by Artellia** [SuperCoder7979/ecotones#1]
It doesn't seem to use the vanilla biomes or anything added by Vanilla+ Biomes.

**Comment by SuperCoder7979** [comment]
Unfortunately, this is intended- The premise of ecotones is a biome overhaul that doesn't use any vanilla biomes apart from oceans, as they would feel out of place. So this is a feature and not a bug.

**Comment by Artellia** [comment]
oh, that's somewhat unfortunate. I like them both, though I think Ecotones edges out Vanilla+ due to the nicer terrain. May I suggest more snowy biomes for Ecotones, if it's not already on the docket? That and I always love me a good redwood forest biome. Great work on all of these mods. I've got a bunch of yours.

**Comment by SuperCoder7979** [comment]
Yeah, snowy biomes are planned! I just haven't gotten the time to implement them, haha. I wanted to get the more tropical portion of the mod complete first. I'm glad you're enjoying the mods :D
