### ISSUE TITLE
Biome Lang entries not present

### ISSUE THREAD

**Issue by AtlasTheProto** [SuperCoder7979/ecotones#10]
Biome names on minimaps like Xaero's Minimap don't seem to have a localized name to use, instead defaulting to the registry name.

![image](https://user-images.githubusercontent.com/17933206/107132899-5e911a80-68b1-11eb-98ec-8acc568fe032.png)

![image](https://user-images.githubusercontent.com/17933206/107132919-6ea8fa00-68b1-11eb-8fbe-da2a292c359d.png)

![image](https://user-images.githubusercontent.com/17933206/107132979-eaa34200-68b1-11eb-8303-59657ef95353.png)

Is this just a case where you haven't gotten around to it yet?

**Comment by SuperCoder7979** [comment]
Yeah, I need to do it sometime, but I don't know when

**Comment by AtlasTheProto** [comment]
[Putting the completed lang-file here so it is not lost.](https://gist.github.com/AtlasTheProto/5313a72e39895da377bfc9bd5a3f4f26)

**Comment by SuperCoder7979** [comment]
Should be fixed with 0.8.1!
