### ISSUE TITLE
[Feature Request] Ecotones biomes will generate in the default world type

### ISSUE THREAD

**Issue by Dakedres** [SuperCoder7979/ecotones#2]
I think it would be really nice if Ecotones biomes could generate in the defualt world type, so you could use it alongside other biome mods if you aren't using Ecotones exclusively.

**Comment by SuperCoder7979** [comment]
This won't be happening as Ecotones uses it's custom world type to have a custom biome distribution, and Ecotones biomes use a design style that won't fit into vanilla minecraft so they would look jarring in the vanilla generator.
