### ISSUE TITLE
Compat bug - But awesome

### ISSUE THREAD

**Issue by AzureMonument** [SuperCoder7979/ecotones#20]
So I've been building a modpack and am currently trying to add ecotones to it (1.17.1, fabric), But I'm also trying to use the Caves & Cliffs datapack. Unfortunately in default generation ecotones is simply overridden by the datapack. As a last resort I tried to use the specific ecotones world generator type with the datapack. Safe to say, it failed to work. _But!_ it didn't crash. Instead I got something much, _much_, cooler.

Welcome to the lands of Apol. 
![2021-08-10_16 28 10](https://user-images.githubusercontent.com/43318292/128930434-94a0af10-ddd4-49b6-87b0-1c81d5df3210.png)
![2021-08-10_16 28 35](https://user-images.githubusercontent.com/43318292/128930472-3619cd7c-d263-4037-a1f4-2b19f67710d4.png)

Non-ocean biomes have floors of gravel and lava, with tiny bits of grass and cobble scattered about.
![2021-08-10_16 29 48](https://user-images.githubusercontent.com/43318292/128930621-9db0fd9a-805a-4439-a3e5-ce80db390c50.png)

A couple blocks under the gravel and stone is bedrock.
![2021-08-10_16 30 46](https://user-images.githubusercontent.com/43318292/128930730-61765f84-d547-42e7-88c2-1e96ea2b00ba.png)

The oceans are nothing but bedrock floors, with the occasional bit of lava.
![2021-08-10_16 32 27](https://user-images.githubusercontent.com/43318292/128930914-e0ff33c5-b6be-4efb-a4c3-15a92518463e.png)

But there  are things under that bedrock, stone. All the way down to void. Though, you can also find subsurface oceans, trapped beneath the bedrock of ocean biomes... (locked in an endless war between the drowned and axolotls...)
![2021-08-10_16 31 34](https://user-images.githubusercontent.com/43318292/128930873-3f4bfe6c-c08d-47f7-b715-052abf324c35.png)
![2021-08-10_16 39 20](https://user-images.githubusercontent.com/43318292/128931906-dc30859b-b246-46ce-a502-393015c19ce2.png)
![2021-08-10_16 39 37](https://user-images.githubusercontent.com/43318292/128931912-92cd60cf-1dd3-49f6-8b5d-7442c144e191.png)

The only wood commonly available is the many mineshafts and ships, floating above the apocalyptic landscape.
![2021-08-10_16 34 47](https://user-images.githubusercontent.com/43318292/128931252-00bb9c30-3f2e-4849-ae37-b2e8fe9ad86a.png)
![2021-08-10_16 33 05](https://user-images.githubusercontent.com/43318292/128931239-c7ced09b-2a32-42f5-8f92-a1b56f704ecf.png)
![2021-08-10_16 33 35](https://user-images.githubusercontent.com/43318292/128931242-f37e4b38-33a9-474c-8931-7140a39261c9.png)

Other things can be found floating in the sky as well- like ruined portals. And beehives, interestingly enough... 
![2021-08-10_16 34 16](https://user-images.githubusercontent.com/43318292/128931314-e757bdfb-4dbd-4dcf-bdac-f429070723dd.png)
![2021-08-10_16 34 21](https://user-images.githubusercontent.com/43318292/128933205-c888cf19-8346-4bdd-b2a8-5d41c61c2735.png)
![2021-08-10_16 36 13](https://user-images.githubusercontent.com/43318292/128931413-2248f253-40c0-4967-aafe-55a70e6d86ce.png)

Other structures, such as the underwater ruins, also exist and you can find buried treasure- though you'll likely have to break bedrock to get to it.
![2021-08-10_16 40 33](https://user-images.githubusercontent.com/43318292/128931946-3cbab295-0937-43e1-81c4-db49939e2cd4.png)

Strongholds can appear as well- massive structures held up by pillars of stone, casting a perpetual, haunted shadow beneath them.
![2021-08-10_16 37 34](https://user-images.githubusercontent.com/43318292/128932163-0549265c-08b6-42eb-b41b-7c96af5c8465.png)
![2021-08-10_16 37 23](https://user-images.githubusercontent.com/43318292/128932180-4d3f55bb-2dd7-4aea-b523-aede7b5bb69e.png)

If you're lucky (or cheating) you can find flying villages, where the last few trees remain, and can access them by water falls cascading from the sky.
![2021-08-10_16 43 48](https://user-images.githubusercontent.com/43318292/128932362-56a6942d-2e95-4893-9d4e-91c44446f2b5.png)
![2021-08-10_16 44 37](https://user-images.githubusercontent.com/43318292/128932487-9343fa58-c856-4ab9-8bcc-cda570878cda.png)
![2021-08-10_16 45 06](https://user-images.githubusercontent.com/43318292/128932525-8f3434a9-5c08-4922-b304-a5ac1c258af8.png)

It's a dangerous, hazardous world, can you rebuild it? :P

Anyway. Is there a way I can get the new cave gen alongside ecotones? It's really the only thing I'm after atm.

**Comment by FarLanderCraft** [comment]
Please this must become a feature.

**Comment by SuperCoder7979** [comment]
This has been fixed. Thank you for the report!
