### ISSUE TITLE
[Suggestion] Add a config option for smooth bedrock

### ISSUE THREAD

**Issue by dandin87** [SuperCoder7979/ecotones#22]
Noticed Ecotones is using its own bedrock generator which of course means the mod https://github.com/haykam821/Smoother-Bedrock is not smoothing the bedrock. I know you don't have a config yet, but I think it would be nice to have an option to have a smooth bedrock layer, or alternatively use the vanilla bedrock layer so that other mods can modify it. Whichever makes more sense/easier to implement.

https://github.com/SuperCoder7979/ecotones/blob/985d1ecc908f53665afd3bd24bb23621baf6299d/src/main/java/supercoder79/ecotones/world/gen/BaseEcotonesChunkGenerator.java#L306

**Comment by haykam821** [comment]
[Version 1.0.2](https://github.com/haykam821/Smoother-Bedrock/releases/tag/1.0.2) of Smoother Bedrock applies to Ecotones chunk generators.

**Comment by dandin87** [comment]
Going to close this, since Haykam added compatibility for Ecotones.
