### ISSUE TITLE
Adjacent Ocean to The Pits causes suspended water in v0.4.4

### ISSUE THREAD

**Issue by Danklor** [SuperCoder7979/ecotones#4]
See attached screenshot. There is no crash or error message and the world is still completely playable.

![2020-06-28_14 57 19](https://user-images.githubusercontent.com/9893553/86004725-b2fe1e80-b9e1-11ea-9216-aeea049054ad.png)

**Comment by SuperCoder7979** [comment]
Yeah.... unfortunately this is a problem with my biome layout manager. Fixing this would need a rewrite of the existing biome generator, but I promise I'll get to it eventually.

**Comment by Danklor** [comment]
Just rechecked with Ecotones 0.5.1. At least it's not on the beach, but The Pits can still form in the ocean.

![2020-08-07_02 45 36](https://user-images.githubusercontent.com/9893553/89618300-d0809c80-d859-11ea-8b53-bbfc02419fd7.png)

**Comment by SuperCoder7979** [comment]
Well, crap. I thought this was fixed.... I'll take another look.
