### ISSUE TITLE
Unregistered stuff

### ISSUE THREAD

**Issue by RDKRACZ** [SuperCoder7979/ecotones#8]
According to Blame:
ecotones:drainage

**Comment by SuperCoder7979** [comment]
It should be registered. May I see the full log?

**Comment by RDKRACZ** [comment]
After reporting other unregistered stuff to other dev it seems that there is something wrong with the Blame mod. I will report this to them.

**Comment by TelepathicGrunt** [comment]
The other dev was wrong and their stuff wasnt registered after all lol. I'll take a look at ecotones to see what's up with the drainage. hang on.

**Comment by TelepathicGrunt** [comment]
@SuperCoder7979 Found it

https://github.com/SuperCoder7979/ecotones/blob/e59312d5a49e179c417dce4fb483bb3feb354fd3/src/main/java/supercoder79/ecotones/world/biome/BiomeUtil.java#L74

The configuredfeature form is not registered. The whole thing will need to be registered to BuiltinRegistries.CONFIGURED_FEATURE 
`EcotonesFeatures.DRAINAGE.configure(FeatureConfig.DEFAULT).decorate(EcotonesDecorators.DRAINAGE_DECORATOR.configure(DecoratorConfig.DEFAULT))`

**Comment by SuperCoder7979** [comment]
Fixed in 0.7.1. Thanks for the report!
